version: '3.8'

services:

  [node_service]:
      container_name: [node-service]
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "3000:3000" # change the port on the left to the port you want to use
      volumes:
        - ./:/app
      environment: # TODO: set the environement variable to the values you desire
        DB_HOST: [hostname (traefik) or IP]
        DB_USER: [user]
        DB_PASSWORD: [password]
        DB_NAME: [Schema_Name]
        PORT: 3000

volumes:
  db_data:
