version: '3.8'

services:

  nodets:
      build: # TODO: change ts to the name of the folder it's in
        context: .
        dockerfile: ts/Dockerfile.nodets
      restart: unless-stopped
      depends_on:
        - db
      ports:
        - "3000:3000"
      volumes:
        - ./ts:/app
      environment: # TODO: set the environement variable to the values you desire
        DB_HOST: db
        DB_USER: user
        DB_PASSWORD: password
        DB_NAME: Schema_Name
        PORT: 3000

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment: # TODO: set the environement variable to the values you desire
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: Schema_Name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Forwarding MariaDB port for external access
    volumes:
      - db_data:/var/lib/mysql  # Persist data
      
  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"  # Forwarding phpMyAdmin port for external access
    environment:
      PMA_HOST: db  # Use the service name as the host
      MYSQL_ROOT_PASSWORD: example_root_password  # TODO: change password accordingly to what you had set up above

volumes:
  db_data:
